USE [master]
GO

/****** Object:  Database [gpsstation2]    Script Date: 17/06/2023 17:19:52 ******/
CREATE DATABASE [gpsstation2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gpsstation2', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL12.TEW_SQLEXPRESS\MSSQL\DATA\gpsstation2.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'gpsstation2_log', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL12.TEW_SQLEXPRESS\MSSQL\DATA\gpsstation2_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gpsstation2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gpsstation2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gpsstation2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gpsstation2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gpsstation2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gpsstation2] SET ARITHABORT OFF 
GO

ALTER DATABASE [gpsstation2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gpsstation2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gpsstation2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gpsstation2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gpsstation2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gpsstation2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gpsstation2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gpsstation2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gpsstation2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gpsstation2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [gpsstation2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gpsstation2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gpsstation2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gpsstation2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gpsstation2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gpsstation2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gpsstation2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gpsstation2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [gpsstation2] SET  MULTI_USER 
GO

ALTER DATABASE [gpsstation2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gpsstation2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [gpsstation2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [gpsstation2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [gpsstation2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [gpsstation2] SET  READ_WRITE 
GO


USE [gpsstation2]
GO

/****** Object:  Table [dbo].[dispositivo]    Script Date: 17/06/2023 17:20:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[dispositivo](
	[Id] [varchar](36) NOT NULL,
	[Nome] [varchar](50) NULL,
	[Latitude] [varchar](10) NULL,
	[Longitude] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [gpsstation2]
/****** Object:  Table [dbo].[localizacao]    Script Date: 17/06/2023 17:20:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[localizacao](
	[IdDispositivo] [varchar](36) NOT NULL,
	[DataHora] [datetime] NOT NULL,
	[Latitude] [varchar](10) NOT NULL,
	[Longitude] [varchar](10) NOT NULL
) ON [PRIMARY]
GO

USE [gpsstation2]
GO

/****** Object:  Table [dbo].[usuario]    Script Date: 17/06/2023 17:21:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[usuario](
	[Nome] [varchar](50) NOT NULL,
	[Senha] [varchar](8) NOT NULL,
	[Id] [varchar](36) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO